// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqPCQMZRI8ghCSseEMw5DC64pxLk2OJ_E',
    appId: '1:545296444047:web:cdc2f7c6757bf2cbf6defa',
    messagingSenderId: '545296444047',
    projectId: 'farchis-ceeb4',
    authDomain: 'farchis-ceeb4.firebaseapp.com',
    storageBucket: 'farchis-ceeb4.firebasestorage.app',
    measurementId: 'G-CS0WBPVME2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr1sLSTziD2TkLsaZTPTIHyPiiOJsPyQM',
    appId: '1:545296444047:android:93c64faf2d72195cf6defa',
    messagingSenderId: '545296444047',
    projectId: 'farchis-ceeb4',
    storageBucket: 'farchis-ceeb4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtUYqjxAYwJV4ygt_eFrDd0-PowRLTOao',
    appId: '1:545296444047:ios:dbdb8a8f90e74fa5f6defa',
    messagingSenderId: '545296444047',
    projectId: 'farchis-ceeb4',
    storageBucket: 'farchis-ceeb4.firebasestorage.app',
    iosBundleId: 'com.example.farchisApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtUYqjxAYwJV4ygt_eFrDd0-PowRLTOao',
    appId: '1:545296444047:ios:dbdb8a8f90e74fa5f6defa',
    messagingSenderId: '545296444047',
    projectId: 'farchis-ceeb4',
    storageBucket: 'farchis-ceeb4.firebasestorage.app',
    iosBundleId: 'com.example.farchisApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqPCQMZRI8ghCSseEMw5DC64pxLk2OJ_E',
    appId: '1:545296444047:web:19a00b0a82055fdff6defa',
    messagingSenderId: '545296444047',
    projectId: 'farchis-ceeb4',
    authDomain: 'farchis-ceeb4.firebaseapp.com',
    storageBucket: 'farchis-ceeb4.firebasestorage.app',
    measurementId: 'G-NK3P999T8W',
  );
}
